webserver:
    image: mozdata/telemetry-airflow
    restart: always
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
        - AIRFLOW_ENABLE_AUTH
        - AWS_REGION
        - EMR_KEY_NAME
        - EMR_FLOW_ROLE
        - EMR_SERVICE_ROLE
        - EMR_INSTANCE_TYPE
        - SPARK_BUCKET
        - AIRFLOW_BUCKET
        - PRIVATE_OUTPUT_BUCKET
        - PUBLIC_OUTPUT_BUCKET
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - DB_URI
        - DB_USER
        - DB_PASSWORD
        - SMTP_HOST
        - SMTP_USER
        - SMTP_PASSWORD
    ports:
        - "8080:8080"
    links:
        - scheduler:scheduler
    command: webserver

scheduler:
    image: mozdata/telemetry-airflow
    restart: always
    mem_limit: 4294967296
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
        - AIRFLOW_ENABLE_AUTH
        - AWS_REGION
        - EMR_KEY_NAME
        - EMR_FLOW_ROLE
        - EMR_SERVICE_ROLE
        - EMR_INSTANCE_TYPE
        - SPARK_BUCKET
        - AIRFLOW_BUCKET
        - PRIVATE_OUTPUT_BUCKET
        - PUBLIC_OUTPUT_BUCKET
        - COMMAND
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - DB_URI
        - DB_USER
        - DB_PASSWORD
        - SMTP_HOST
        - SMTP_USER
        - SMTP_PASSWORD
